version: '3'

volumes:
   mongodb:

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
    
  app:
    build: ./
    container_name: quark_v3_output
    restart: always
    volumes:
      - ./prod.env:/usr/src/app/.env
    ports:
      - '80:3000'
    depends_on: 
      - mongo